In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import data_generation_functions as dgf

## Goal

Check all pairwise combinations of N samples in the "fairest" way possible, where "fair" means, that the waiting time between checks is minimal for each sample.

In [46]:
def create_table(N):
    table={}
    
    shift=1
    first=True
    for j in range(N-1):    
        row=["-" for i in range(N)]
    
        pattern=np.array(dgf._shiftroll(shift,N))
        if first:
            extra="a"
        else:
            extra="b"
            end=N-len(pattern)
            pattern= (pattern+shift)[:end]
    
        for i in pattern:
            row[i]=(i+shift)%N
    
        table["shift "+str(shift)+" "+extra]=row
        
        if not first:
            shift+=1
        first=not first
    return table

In [48]:
N=16
print("Combination table for all pairwise checks")
print("in sequential order left to right and top to bottom")
pd.DataFrame.from_dict(create_table(N), orient='index',columns=np.arange(N))

Combination table for all pairwise checks
in sequential order left to right and top to bottom

          0  1   2   3   4   5   6   7   8   9   10  11  12  13  14 15
shift 1 a  1  -   3   -   5   -   7   -   9   -  11   -  13   -  15  -
shift 1 b  -  2   -   4   -   6   -   8   -  10   -  12   -  14   -  0
shift 2 a  2  3   -   -   6   7   -   -  10  11   -   -  14  15   -  -
shift 2 b  -  -   4   5   -   -   8   9   -   -  12  13   -   -   0  1
shift 3 a  3  4   5   -   -   -   9  10  11   -   -   -  15   0   1  -
shift 3 b  -  -   -   6   7   8   -   -   -  12  13  14   -   -   -  2
shift 4 a  4  5   6   7   -   -   -   -  12  13  14  15   -   -   -  -
shift 4 b  -  -   -   -   8   9  10  11   -   -   -   -   0   1   2  3
shift 5 a  5  6   7   8   9   -   -   -   -   -  15   0   1   2   3  -
shift 5 b  -  -   -   -   -  10  11  12  13  14   -   -   -   -   -  4
shift 6 a  6  7   8   9  10  11   -   -   -   -   -   -   2   3   4  5
shift 6 b  -  -   -   -   -   -  12  13  14  15   0   1   -   -   -  -
shift 7 a  7  8   9  10  11  12  13   -   -   -   -   -   -   -   5  6
shift 7 b  -  -   -   -   -   -   -  14  15   0   1   2   3   4   -  -
shift 8 a  8  9  10  11  12  13  14  15   -   -   -   -   -   -   -  -

In [49]:
N=5
print("Combination table for all pairwise checks")
print("in sequential order left to right and top to bottom")
pd.DataFrame.from_dict(create_table(N), orient='index',columns=np.arange(N))

Combination table for all pairwise checks
in sequential order left to right and top to bottom

           0  1  2  3  4
shift 1 a  1  -  3  -  0
shift 1 b  -  2  -  4  -
shift 2 a  2  3  -  -  1
shift 2 b  -  -  4  0  -